FROM quay.io/fedora/fedora:39
# Base setup
RUN sed -i "/tsflags=nodocs/d" /etc/dnf/dnf.conf
RUN sed -i "s/installonly_limit.*/installonly_limit=6/g" /etc/dnf/dnf.conf
RUN echo "max_parallel_downloads=20" >> /etc/dnf/dnf.conf
RUN dnf update -y

# Install the needed IDEs, base and devel packages
RUN dnf install git neovim plocate ansible dotnet-sdk-7.0 -y
RUN dnf install fribidi-devel libcurl-devel libjpeg-turbo-devel libtiff-devel openssl-devel -y
RUN dnf install python python-pip lm_sensors tig tree -y

# Install VSCodium
RUN rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
RUN printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | tee -a /etc/yum.repos.d/vscodium.repo 
RUN dnf install codium -y

# Install KIND and kubectl for Kubernetes interaction
# kind
RUN bash -c "[ $(uname -m) = x86_64 ] && curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64" \
	bash -c "[ $(uname -m) = aarch64 ] && curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-arm64"
RUN chmod +x /usr/local/bin/kind

# kubectl
RUN bash -c "[ $(uname -m) = x86_64 ] && curl -Lo /usr/local/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
        bash -c "[ $(uname -m) = aarch64 ] && curl -Lo /usr/local/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
RUN chmod +x /usr/local/bin/kubectl

# Enable RPMFusion
RUN dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y 

# Install LaTeX
RUN dnf install texlive-scheme-full -y

# Install codecs
RUN dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
