FROM registry.fedoraproject.org/fedora:37

# Base setup
RUN sed -i "/tsflags=nodocs/d" /etc/dnf/dnf.conf
RUN dnf update -y
RUN dnf install git wget nmap neovim vim gcc-c++ -y

# Install the needed base and devel packages
RUN dnf install fribidi-devel libcurl-devel libtiff-devel openssl-devel R-base libxml2-devel fontconfig-devel harfbuzz-devel freetype-devel libpng-devel libjpeg-turbo-devel R-core R-devel R-core-devel -y

# Install RStudio
RUN dnf install rstudio-desktop -y
