[main]
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
power-saver=thinkpad-battery
balanced=balanced
performance=throughput-performance

[battery]
balanced=thinkpad-battery
power-saver=thinkpad-powersave
