#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

case "$1" in
    post)
        echo "Wake fix started at $(date)" >> /var/log/tuned-wake-fix.log
        
        sleep 2
        
        if [ -f /sys/firmware/acpi/platform_profile ]; then
            echo performance > /sys/firmware/acpi/platform_profile 2>> /var/log/tuned-wake-fix.log
        fi
        sleep 0.5
        
        /usr/sbin/tuned-adm profile thinkpad-battery >> /var/log/tuned-wake-fix.log 2>&1
        
        echo "Wake fix finished with status $?" >> /var/log/tuned-wake-fix.log
        ;;
esac
