[main]
summary=Battery saving battery profile for ThinkPad T14 Gen 4 (i5-1335U)
include=thinkpad-battery

[cpu]
governor=powersave
dynamic_tuning=true
energy_perf_bias=power
energy_performance_preference=power
energy_performance_preference_max_perf=power
