[main]
summary=Optimized balanced battery profile for ThinkPad T14 Gen 4 (i5-1335U)
dynamic_tuning = 1

[cpu]
governor=powersave
dynamic_tuning=true
energy_perf_bias=balance_power
energy_performance_preference=balance_power
energy_performance_preference_max_perf=balance_performance

[audio]
type=audio
timeout=10

[video]
type=video
panel_power_savings=1

[usb]
type=usb
autosuspend=1

[ee_pcie]
aspm=powersave

[sysctl]
kernel.nmi_watchdog=0
vm.laptop_mode=2
vm.dirty_writeback_centisecs=6000
vm.dirty_expire_centisecs=6000
