name: Build ARM Images - Ubuntu, Development, RStudio and General 
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '5 4 * * *' 
jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d%m%Y')"
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker.io container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./podman-images/Containerfile.ubuntu
          push: true
          platforms: linux/arm64
          tags: johngh/distrobox-images:ubuntu-base-arm, johngh/distrobox-images:ubuntu-base-24-arm, johngh/distrobox-images:ubuntu-base-24-arm-${{ steps.date.outputs.date }}
  build-development:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d%m%Y')"
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker.io container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./podman-images/Containerfile.development
          push: true
          platforms: linux/arm64
          tags: johngh/distrobox-images:development-base-arm, johngh/distrobox-images:development-base-42-arm, johngh/distrobox-images:development-base-42-arm-${{ steps.date.outputs.date }}
  build-general:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d%m%Y')"
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker.io container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./podman-images/Containerfile.general
          push: true
          platforms: linux/arm64
          tags: johngh/distrobox-images:general-base-arm, johngh/distrobox-images:general-base-42-arm, johngh/distrobox-images:general-base-42-arm-${{ steps.date.outputs.date }}
  build-rstudio:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d%m%Y')"
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker.io container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./podman-images/Containerfile.rstudio
          push: true
          platforms: linux/arm64
          tags: johngh/distrobox-images:rstudio-base-arm, johngh/distrobox-images:rstudio-base-41-arm, johngh/distrobox-images:rstudio-base-41-arm-${{ steps.date.outputs.date }}
