name: Build RStudio image for AMD64
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '5 4 * * *' 
jobs:
  build-rstudio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker.io container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./podman-images/Containerfile.rstudio
          push: true
          platforms: linux/amd64
          tags: johngh/distrobox-images:rstudio-base, johngh/distrobox-images:rstudio-base-amd64, johngh/distrobox-images:rstudio-base-38, johngh/distrobox-images:rstudio-base-38-${{ github.workflow.sha }}
